### ISSUE TITLE
[Feedback] Getting started - /docs/getting-started/ - Windows 10 comes with an SSH client these days

### ISSUE THREAD

**Issue by HenrikBengtsson** [stanford-rc/www.sherlock.stanford.edu#129]
<https://www.sherlock.stanford.edu/docs/getting-started/#windows> says:

"Microsoft Windows doesn't provide any SSH client by default. ..."

That's no longer the case - a fully functional `ssh` client is installed by default on MS Windows 10 since around build 1709 (October 2017).

**Comment by kcgthb** [comment]
That's very true, thanks for spotting this and reporting the outdated information. This is fixed in c7be3d41e233e4b5f4be9acbe3058cdcb8f9cfe5
