### ISSUE TITLE
[Feedback] Storage <small>on Sherlock</small> - /docs/storage/

### ISSUE THREAD

**Issue by amehtaSF** [stanford-rc/www.sherlock.stanford.edu#131]
It is unclear where I should store large datasets while I am actively using them to run jobs on sherlock

**Comment by kcgthb** [comment]
See https://www.sherlock.stanford.edu/docs/storage/#where-should-i-store-my-files
Please make sure to contact [srcc-support@stanford.edu](mailto:srcc-support@stanford.edu) for any support request.
