### ISSUE TITLE
maintenance period typo?

### ISSUE THREAD

**Issue by tbenst** [stanford-rc/www.sherlock.stanford.edu#36]
>  As often as possible, maintenances will take place on the first Tuesday of every month, from 8am to 12am, and will be announced 2 weeks in advance, through the usual communication channels. In case an exceptional amount of work is required, the maintenance window could be extended to 10 hours (from 8am to 6pm).

> Q: Why Tuesdays 8am-12am? Why not do this late at night?

It appears this should say 8am-12pm

**Comment by kcgthb** [comment]
Good catch, thank you!
The time notation has been updated to use a less error-prone ISO 8601 format :)

**Comment by kcgthb** [comment]
Closing #36
